### ISSUE TITLE
안녕하세요! 해당 밋업 오프라인 참가자입니다. 예제는 날아간건가요?

### ISSUE THREAD

**Issue by DaengDo** [utilForever/2024-CppKorea-HandsOn-Concurrency#3]
cpp 코리아 핸즈온 세션 참가했던 강윤석입니다. 바쁘실텐데 요청드려 죄송합니다.

싱글 스레드 스택을 멀티 스레드 스택 구조로 변경하는 실습을 시간 관계상 못한것이 무척 아쉬운데

해당 코드들은 비공개 혹은 라이브 코딩 계획이었기 때문에 취소된 것인지 궁금합니다.

**Comment by DaengDo** [comment]
그리고 atomic_flag가 임계 영역 내부에서 사용되는 플래그 값이 아니고 임계 영역의 코드를 제어하기 위한 값이라는데 결국 락이랑 뭐가 다른지 잘 이해가 가지는 않네요. 지금은 이해의 대상으로 두기보다 받아들임(?)의 대상으로 두고 있습니다.

**Comment by utilForever** [comment]
@DaengDo 안녕하세요, 강윤석님. 옥찬호입니다.

우선 핸즈온 세션 참가해주셔서 감사합니다. 예제 코드는 올려뒀는데, 실습 코드를 아직 올리지 않았었네요. 죄송합니다.
방금 실습 코드로 진행 예정이었던 '망델브로 집합' 프로젝트의 베이스 코드와 멀티 스레드, 락 프리로 변경한 코드를 올려뒀습니다.
스택 프로젝트도 뒤이어 오늘 중으로 올려두도록 하겠습니다. 감사합니다.
